"""initial schema

Revision ID: 17b107e830d6
Revises: 
Create Date: 2026-04-30 15:10:13.142393

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '17b107e830d6'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('hr_admins',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('hr_admins', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_hr_admins_email'), ['email'], unique=True)

    op.create_table('passages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('difficulty', sa.String(length=20), nullable=False),
    sa.Column('topic', sa.String(length=100), nullable=True),
    sa.Column('word_count', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('passages', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_passages_difficulty'), ['difficulty'], unique=False)

    op.create_table('speaking_topics',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('prompt_text', sa.Text(), nullable=False),
    sa.Column('difficulty', sa.String(length=20), nullable=False),
    sa.Column('category', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('speaking_topics', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_speaking_topics_difficulty'), ['difficulty'], unique=False)

    op.create_table('writing_topics',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('prompt_text', sa.Text(), nullable=False),
    sa.Column('difficulty', sa.String(length=20), nullable=False),
    sa.Column('min_words', sa.Integer(), nullable=False),
    sa.Column('max_words', sa.Integer(), nullable=False),
    sa.Column('category', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('writing_topics', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_writing_topics_difficulty'), ['difficulty'], unique=False)

    op.create_table('invitations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('token', sa.String(length=64), nullable=False),
    sa.Column('candidate_email', sa.String(length=255), nullable=False),
    sa.Column('candidate_name', sa.String(length=100), nullable=False),
    sa.Column('difficulty', sa.String(length=20), nullable=False),
    sa.Column('hr_admin_id', sa.Integer(), nullable=False),
    sa.Column('passage_id', sa.Integer(), nullable=True),
    sa.Column('assigned_question_ids', sa.JSON(), nullable=True),
    sa.Column('assigned_topic_ids', sa.JSON(), nullable=True),
    sa.Column('assigned_writing_topic_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('submitted_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['assigned_writing_topic_id'], ['writing_topics.id'], ),
    sa.ForeignKeyConstraint(['hr_admin_id'], ['hr_admins.id'], ),
    sa.ForeignKeyConstraint(['passage_id'], ['passages.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('invitations', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_invitations_hr_admin_id'), ['hr_admin_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_invitations_token'), ['token'], unique=True)

    op.create_table('questions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('passage_id', sa.Integer(), nullable=True),
    sa.Column('question_type', sa.String(length=20), nullable=False),
    sa.Column('difficulty', sa.String(length=20), nullable=False),
    sa.Column('stem', sa.Text(), nullable=False),
    sa.Column('options', sa.JSON(), nullable=False),
    sa.Column('correct_answer', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.CheckConstraint('correct_answer >= 0 AND correct_answer <= 3', name='ck_questions_correct_answer_range'),
    sa.ForeignKeyConstraint(['passage_id'], ['passages.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('questions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_questions_difficulty'), ['difficulty'], unique=False)
        batch_op.create_index(batch_op.f('ix_questions_passage_id'), ['passage_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_questions_question_type'), ['question_type'], unique=False)

    op.create_table('audio_recordings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('invitation_id', sa.Integer(), nullable=False),
    sa.Column('topic_id', sa.Integer(), nullable=False),
    sa.Column('file_path', sa.String(length=500), nullable=False),
    sa.Column('mime_type', sa.String(length=50), nullable=False),
    sa.Column('duration_seconds', sa.Integer(), nullable=True),
    sa.Column('transcript', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['invitation_id'], ['invitations.id'], ),
    sa.ForeignKeyConstraint(['topic_id'], ['speaking_topics.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('audio_recordings', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_audio_recordings_invitation_id'), ['invitation_id'], unique=False)

    op.create_table('mcq_answers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('invitation_id', sa.Integer(), nullable=False),
    sa.Column('question_id', sa.Integer(), nullable=False),
    sa.Column('selected_option', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['invitation_id'], ['invitations.id'], ),
    sa.ForeignKeyConstraint(['question_id'], ['questions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('mcq_answers', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_mcq_answers_invitation_id'), ['invitation_id'], unique=False)

    op.create_table('scores',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('invitation_id', sa.Integer(), nullable=False),
    sa.Column('reading_score', sa.Integer(), nullable=True),
    sa.Column('reading_correct', sa.Integer(), nullable=True),
    sa.Column('reading_total', sa.Integer(), nullable=True),
    sa.Column('writing_breakdown', sa.JSON(), nullable=True),
    sa.Column('writing_score', sa.Integer(), nullable=True),
    sa.Column('speaking_breakdown', sa.JSON(), nullable=True),
    sa.Column('speaking_score', sa.Integer(), nullable=True),
    sa.Column('total_score', sa.Integer(), nullable=True),
    sa.Column('rating', sa.String(length=30), nullable=True),
    sa.Column('ai_feedback', sa.Text(), nullable=True),
    sa.Column('scored_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['invitation_id'], ['invitations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('scores', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_scores_invitation_id'), ['invitation_id'], unique=True)

    op.create_table('writing_responses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('invitation_id', sa.Integer(), nullable=False),
    sa.Column('topic_id', sa.Integer(), nullable=False),
    sa.Column('essay_text', sa.Text(), nullable=False),
    sa.Column('word_count', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['invitation_id'], ['invitations.id'], ),
    sa.ForeignKeyConstraint(['topic_id'], ['writing_topics.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('writing_responses', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_writing_responses_invitation_id'), ['invitation_id'], unique=True)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('writing_responses', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_writing_responses_invitation_id'))

    op.drop_table('writing_responses')
    with op.batch_alter_table('scores', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_scores_invitation_id'))

    op.drop_table('scores')
    with op.batch_alter_table('mcq_answers', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_mcq_answers_invitation_id'))

    op.drop_table('mcq_answers')
    with op.batch_alter_table('audio_recordings', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_audio_recordings_invitation_id'))

    op.drop_table('audio_recordings')
    with op.batch_alter_table('questions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_questions_question_type'))
        batch_op.drop_index(batch_op.f('ix_questions_passage_id'))
        batch_op.drop_index(batch_op.f('ix_questions_difficulty'))

    op.drop_table('questions')
    with op.batch_alter_table('invitations', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_invitations_token'))
        batch_op.drop_index(batch_op.f('ix_invitations_hr_admin_id'))

    op.drop_table('invitations')
    with op.batch_alter_table('writing_topics', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_writing_topics_difficulty'))

    op.drop_table('writing_topics')
    with op.batch_alter_table('speaking_topics', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_speaking_topics_difficulty'))

    op.drop_table('speaking_topics')
    with op.batch_alter_table('passages', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_passages_difficulty'))

    op.drop_table('passages')
    with op.batch_alter_table('hr_admins', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_hr_admins_email'))

    op.drop_table('hr_admins')
    # ### end Alembic commands ###
